### ISSUE TITLE
crash when report throws

### ISSUE THREAD

**Issue by zhaar** [dgellow/tesuto#4]
This piece of code

```
const t = require('tesuto');

t.report("exception crash", function() {
    throw "should crash tesuto"
})
```

confuses the error reporting and prints the error

```
var match = e.stack.match(new RegExp(
                   ^

TypeError: Cannot read property 'match' of undefined
```

**Comment by dgellow** [comment]
Should be fixed with https://github.com/dgellow/tesuto/commit/da9c9d4cfaeb0f2986667dfc06e52f2ef6ba402a. I pushed a version `2.0.2` to npm right away. I'm closing the issue, you can reopen if you still see the problem.
